"""CPT and ICD-10 display labels for the supplementary code tables."""
CAT_LABEL = {
    "intraspinal_tumor_excision": "Intraspinal tumor excision",
    "arthrodesis_fusion": "Arthrodesis / fusion",
    "corpectomy_vertebral_body_resection": "Corpectomy / vertebral body resection",
    "decompression_laminectomy": "Decompression / laminectomy",
    "instrumentation_or_unlisted": "Instrumentation / unlisted spine",
    "partial_vertebral_excision_osteotomy": "Partial vertebral excision / osteotomy",
}
CAT_ORDER = ["intraspinal_tumor_excision", "corpectomy_vertebral_body_resection",
            "decompression_laminectomy", "arthrodesis_fusion",
            "partial_vertebral_excision_osteotomy", "instrumentation_or_unlisted"]

CPT_DESC = {
    # intraspinal tumor excision (laminectomy for biopsy/excision of intraspinal neoplasm)
    "63275": "Laminectomy for excision of intraspinal neoplasm, extradural, cervical",
    "63276": "Laminectomy for excision of intraspinal neoplasm, extradural, thoracic",
    "63277": "Laminectomy for excision of intraspinal neoplasm, extradural, lumbar",
    "63278": "Laminectomy for excision of intraspinal neoplasm, extradural, sacral",
    "63280": "Laminectomy for excision of intraspinal neoplasm, intradural extramedullary, cervical",
    "63281": "Laminectomy for excision of intraspinal neoplasm, intradural extramedullary, thoracic",
    "63282": "Laminectomy for excision of intraspinal neoplasm, intradural extramedullary, lumbar",
    "63283": "Laminectomy for excision of intraspinal neoplasm, intradural extramedullary, sacral",
    "63285": "Laminectomy for excision of intraspinal neoplasm, intradural intramedullary, cervical",
    "63286": "Laminectomy for excision of intraspinal neoplasm, intradural intramedullary, thoracic",
    "63287": "Laminectomy for excision of intraspinal neoplasm, intradural intramedullary, thoracolumbar",
    "63290": "Laminectomy for excision of intraspinal neoplasm, combined extradural-intradural, any level",
    # corpectomy / vertebral body resection
    "63081": "Vertebral corpectomy, anterior, cervical, single segment",
    "63082": "Vertebral corpectomy, anterior, cervical, each additional segment",
    "63085": "Vertebral corpectomy, transthoracic, thoracic, single segment",
    "63087": "Vertebral corpectomy, combined thoracolumbar, single segment",
    "63090": "Vertebral corpectomy, anterolateral, lumbar, single segment",
    "63091": "Vertebral corpectomy, anterolateral, lumbar, each additional segment",
    "63101": "Vertebral corpectomy, lateral extracavitary, thoracic, single segment",
    "63102": "Vertebral corpectomy, lateral extracavitary, lumbar, single segment",
    "63103": "Vertebral corpectomy, lateral extracavitary, each additional segment",
    "63300": "Vertebral corpectomy for intraspinal lesion, extradural, cervical",
    "63301": "Vertebral corpectomy for intraspinal lesion, extradural, thoracic (transthoracic)",
    "63302": "Vertebral corpectomy for intraspinal lesion, extradural, thoracic (thoracolumbar)",
    "63303": "Vertebral corpectomy for intraspinal lesion, extradural, lumbar/sacral",
    "63304": "Vertebral corpectomy for intraspinal lesion, intradural, cervical",
    "63305": "Vertebral corpectomy for intraspinal lesion, intradural, thoracic (transthoracic)",
    "63307": "Vertebral corpectomy for intraspinal lesion, intradural, lumbar/sacral",
    # decompression / laminectomy
    "63001": "Laminectomy with decompression, cervical, 1-2 segments",
    "63003": "Laminectomy with decompression, thoracic, 1-2 segments",
    "63005": "Laminectomy with decompression, lumbar, 1-2 segments",
    "63011": "Laminectomy with decompression, sacral",
    "63012": "Laminectomy, removal of abnormal facets/pars (Gill type), lumbar",
    "63015": "Laminectomy with decompression, cervical, more than 2 segments",
    "63016": "Laminectomy with decompression, thoracic, more than 2 segments",
    "63017": "Laminectomy with decompression, lumbar, more than 2 segments",
    "63020": "Laminotomy with decompression, cervical, 1 interspace",
    "63030": "Laminotomy with decompression, lumbar, 1 interspace",
    "63045": "Laminectomy, facetectomy and foraminotomy, cervical, single segment",
    "63046": "Laminectomy, facetectomy and foraminotomy, thoracic, single segment",
    "63047": "Laminectomy, facetectomy and foraminotomy, lumbar, single segment",
    "63048": "Laminectomy, facetectomy and foraminotomy, each additional segment",
    "63051": "Laminectomy with reconstruction (laminoplasty), cervical",
    "63055": "Transpedicular decompression of spinal cord, thoracic, single segment",
    "63056": "Transpedicular decompression of spinal cord, lumbar, single segment",
    "63064": "Costovertebral approach with decompression, thoracic, single segment",
    "63075": "Discectomy, anterior, cervical, single interspace",
    "63076": "Discectomy, anterior, cervical, each additional interspace",
    "63077": "Discectomy, anterior, thoracic, single interspace",
    "63170": "Laminectomy with myelotomy",
    "63265": "Laminectomy for excision of intraspinal lesion, extradural, cervical",
    "63266": "Laminectomy for excision of intraspinal lesion, extradural, thoracic",
    "63267": "Laminectomy for excision of intraspinal lesion, extradural, lumbar",
    "63268": "Laminectomy for excision of intraspinal lesion, extradural, sacral",
    "63270": "Laminectomy for excision of intraspinal lesion, intradural, cervical",
    "63271": "Laminectomy for excision of intraspinal lesion, intradural, thoracic",
    "63272": "Laminectomy for excision of intraspinal lesion, intradural, lumbar",
    # arthrodesis / fusion
    "22532": "Arthrodesis, lateral extracavitary, thoracic",
    "22533": "Arthrodesis, lateral extracavitary, lumbar",
    "22534": "Arthrodesis, lateral extracavitary, thoracic/lumbar, each additional segment",
    "22551": "Arthrodesis, anterior interbody with decompression, cervical below C2",
    "22552": "Arthrodesis, anterior interbody, cervical below C2, each additional interspace",
    "22554": "Arthrodesis, anterior interbody, cervical below C2",
    "22556": "Arthrodesis, anterior interbody, thoracic",
    "22558": "Arthrodesis, anterior interbody, lumbar",
    "22586": "Arthrodesis, presacral interbody, L5-S1",
    "22590": "Arthrodesis, posterior, craniocervical (occiput to C2)",
    "22595": "Arthrodesis, posterior, atlas-axis (C1-C2)",
    "22600": "Arthrodesis, posterior/posterolateral, cervical below C2, single level",
    "22610": "Arthrodesis, posterior/posterolateral, thoracic, single level",
    "22612": "Arthrodesis, posterior/posterolateral, lumbar, single level",
    "22614": "Arthrodesis, posterior/posterolateral, each additional vertebral segment",
    "22630": "Arthrodesis, posterior interbody, lumbar, single interspace",
    "22633": "Arthrodesis, combined posterior and posterior interbody, lumbar, single interspace",
    "22634": "Arthrodesis, combined posterior and posterior interbody, each additional interspace",
    "22800": "Arthrodesis, posterior, for spinal deformity, up to 6 vertebral segments",
    "22802": "Arthrodesis, posterior, for spinal deformity, 7 to 12 vertebral segments",
    "22804": "Arthrodesis, posterior, for spinal deformity, 13 or more vertebral segments",
    "22830": "Exploration of spinal fusion",
    # partial vertebral excision / osteotomy / drainage
    "22010": "Incision and drainage, deep abscess, posterior spine, cervical/thoracic",
    "22101": "Partial excision of posterior vertebral component for intrinsic bony lesion, thoracic",
    "22102": "Partial excision of posterior vertebral component for intrinsic bony lesion, lumbar",
    "22110": "Partial excision of vertebral body for intrinsic bony lesion, cervical",
    "22112": "Partial excision of vertebral body for intrinsic bony lesion, thoracic",
    "22114": "Partial excision of vertebral body for intrinsic bony lesion, lumbar",
    "22206": "Osteotomy of spine, posterior, 3-column, thoracic",
    "22210": "Osteotomy of spine, posterior, cervical",
    "22212": "Osteotomy of spine, posterior, thoracic",
    "22214": "Osteotomy of spine, posterior, lumbar",
    "22222": "Osteotomy of spine, anterior approach, thoracic",
    "22224": "Osteotomy of spine, anterior approach, lumbar",
    "22325": "Open treatment of vertebral fracture/dislocation, posterior, lumbar",
    "22326": "Open treatment of vertebral fracture/dislocation, posterior, cervical",
    "22327": "Open treatment of vertebral fracture/dislocation, posterior, thoracic",
    # instrumentation / unlisted
    "22840": "Posterior non-segmental instrumentation",
    "22842": "Posterior segmental instrumentation, 3 to 6 vertebral segments",
    "22843": "Posterior segmental instrumentation, 7 to 12 vertebral segments",
    "22845": "Anterior instrumentation, 2 to 3 vertebral segments",
    "22849": "Reinsertion of spinal fixation device",
    "22852": "Removal of posterior segmental instrumentation",
    "22899": "Unlisted procedure, spine",
}

ICD_DESC = {
    "C79.51": "Secondary malignant neoplasm of bone",
    "C79.49": "Secondary malignant neoplasm of other parts of nervous system",
    "C79.5": "Secondary malignant neoplasm of bone and bone marrow, unspecified",
    "C79.9": "Secondary malignant neoplasm, unspecified site",
    "C79.89": "Secondary malignant neoplasm of other specified sites",
    "C79.31": "Secondary malignant neoplasm of brain",
    "C79.4": "Secondary malignant neoplasm of unspecified parts of nervous system",
    "C7B.8": "Other secondary neuroendocrine tumors",
    "C7B.03": "Secondary carcinoid tumors of bone",
    "C79": "Secondary malignant neoplasm (unspecified)",
    "C79.40": "Secondary malignant neoplasm of unspecified part of nervous system",
    "C79.52": "Secondary malignant neoplasm of bone marrow",
    "C79.82": "Secondary malignant neoplasm of genital organs",
    "C7B.1": "Secondary Merkel cell carcinoma",
    "C79.8": "Secondary malignant neoplasm of other specified sites",
    "C79.00": "Secondary malignant neoplasm of unspecified kidney and renal pelvis",
    "C79.81": "Secondary malignant neoplasm of breast",
    "C79.1": "Secondary malignant neoplasm of bladder and other urinary organs",
    "C7B.09": "Secondary carcinoid tumors of other sites",
    "C79.11": "Secondary malignant neoplasm of bladder",
    "C79.3": "Secondary malignant neoplasm of brain and cerebral meninges",
}


